# Generated by Django 4.2.18 on 2025-02-23 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="last_access",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
