# Generated by Django 4.2.18 on 2025-01-26 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_session_appuser_uid_appuser_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='email_verification',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
