# Generated by Django 4.2.18 on 2025-01-28 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_appuser_email_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL),
        ),
    ]
