# Generated by Django 4.2.18 on 2025-03-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userwallet_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwallet",
            name="key",
            field=models.CharField(default="", max_length=500),
        ),
    ]
