# Generated by Django 4.2.18 on 2025-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='network',
            field=models.CharField(default='', max_length=100),
        ),
    ]
