# Generated by Django 4.2.18 on 2025-02-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="avatar_id",
            field=models.IntegerField(default=3),
        ),
    ]
