# Generated by Django 4.2.18 on 2025-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_short', models.CharField(max_length=10)),
                ('coin_long', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('network', models.CharField(default='bep20', max_length=10)),
                ('min', models.FloatField(default=1)),
                ('max', models.FloatField(default=1000)),
            ],
        ),
    ]
