# Generated by Django 4.2.18 on 2025-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=20)),
                ('bank', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('uid', models.CharField(default='', max_length=20)),
                ('account_type', models.CharField(default='bank', max_length=10)),
            ],
        ),
    ]
