# Generated by Django 4.2.18 on 2025-02-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='platform_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
