# Generated by Django 4.2.18 on 2025-02-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_accountdetails_platform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='bank',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='name',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
