# Generated by Django 4.2.18 on 2025-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_accountdetails_bank_alter_accountdetails_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='uid',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
