# Generated by Django 4.2.18 on 2025-02-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_accountdetails_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='platform_type',
            new_name='platform',
        ),
    ]
