# Generated by Django 4.2.18 on 2025-02-20 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_short', models.CharField(max_length=10)),
                ('coin_long', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
                ('network', models.CharField(default='bep20', max_length=10)),
                ('min', models.FloatField(default=1)),
                ('max', models.FloatField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.FloatField(default=0)),
                ('algo', models.FloatField(default=0)),
                ('atom', models.FloatField(default=0)),
                ('avax', models.FloatField(default=0)),
                ('bat', models.FloatField(default=0)),
                ('bch', models.FloatField(default=0)),
                ('bnb', models.FloatField(default=0)),
                ('bond', models.FloatField(default=0)),
                ('btc', models.FloatField(default=0)),
                ('busd', models.FloatField(default=0)),
                ('dash', models.FloatField(default=0)),
                ('doge', models.FloatField(default=0)),
                ('dot', models.FloatField(default=0)),
                ('edu', models.FloatField(default=0)),
                ('eos', models.FloatField(default=0)),
                ('etc', models.FloatField(default=0)),
                ('eth', models.FloatField(default=0)),
                ('ftm', models.FloatField(default=0)),
                ('fxs', models.FloatField(default=0)),
                ('gala', models.FloatField(default=0)),
                ('gtc', models.FloatField(default=0)),
                ('hive', models.FloatField(default=0)),
                ('kava', models.FloatField(default=0)),
                ('link', models.FloatField(default=0)),
                ('ltc', models.FloatField(default=0)),
                ('mana', models.FloatField(default=0)),
                ('matic', models.FloatField(default=0)),
                ('ngn', models.FloatField(default=0)),
                ('neo', models.FloatField(default=0)),
                ('one', models.FloatField(default=0)),
                ('ont', models.FloatField(default=0)),
                ('paxg', models.FloatField(default=0)),
                ('qnt', models.FloatField(default=0)),
                ('shib', models.FloatField(default=0)),
                ('sol', models.FloatField(default=0)),
                ('trx', models.FloatField(default=0)),
                ('ton', models.FloatField(default=0)),
                ('uni', models.FloatField(default=0)),
                ('usdc', models.FloatField(default=0)),
                ('usdt', models.FloatField(default=0)),
                ('wbtc', models.FloatField(default=0)),
                ('xlm', models.FloatField(default=0)),
                ('xmr', models.FloatField(default=0)),
                ('xrp', models.FloatField(default=0)),
                ('yfi', models.FloatField(default=0)),
                ('zec', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(default='1234', max_length=20)),
                ('transaction_type', models.CharField(max_length=10)),
                ('qty', models.FloatField(default=0)),
                ('amount_usd', models.FloatField(default=0)),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('reference', models.CharField(blank=True, max_length=70, null=True)),
                ('hash', models.CharField(blank=True, max_length=70, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('fee', models.FloatField(default=0)),
                ('medium', models.CharField(default='', max_length=10)),
                ('bank', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.userbankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_from', models.FloatField(default=0)),
                ('qty_to', models.FloatField(default=0)),
                ('currency_from', models.CharField(max_length=10)),
                ('currency_to', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
