# Generated by Django 4.2.18 on 2025-01-28 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_short', models.CharField(max_length=10)),
                ('coin_long', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.FloatField(default=0)),
                ('algo', models.FloatField(default=0)),
                ('atom', models.FloatField(default=0)),
                ('avax', models.FloatField(default=0)),
                ('bat', models.FloatField(default=0)),
                ('bch', models.FloatField(default=0)),
                ('bnb', models.FloatField(default=0)),
                ('bond', models.FloatField(default=0)),
                ('btc', models.FloatField(default=0)),
                ('busd', models.FloatField(default=0)),
                ('dash', models.FloatField(default=0)),
                ('doge', models.FloatField(default=0)),
                ('dot', models.FloatField(default=0)),
                ('edu', models.FloatField(default=0)),
                ('eos', models.FloatField(default=0)),
                ('etc', models.FloatField(default=0)),
                ('eth', models.FloatField(default=0)),
                ('ftm', models.FloatField(default=0)),
                ('fxs', models.FloatField(default=0)),
                ('gala', models.FloatField(default=0)),
                ('gtc', models.FloatField(default=0)),
                ('hive', models.FloatField(default=0)),
                ('kava', models.FloatField(default=0)),
                ('link', models.FloatField(default=0)),
                ('ltc', models.FloatField(default=0)),
                ('mana', models.FloatField(default=0)),
                ('matic', models.FloatField(default=0)),
                ('neo', models.FloatField(default=0)),
                ('one', models.FloatField(default=0)),
                ('ont', models.FloatField(default=0)),
                ('paxg', models.FloatField(default=0)),
                ('qnt', models.FloatField(default=0)),
                ('shib', models.FloatField(default=0)),
                ('sol', models.FloatField(default=0)),
                ('trx', models.FloatField(default=0)),
                ('uni', models.FloatField(default=0)),
                ('usdc', models.FloatField(default=0)),
                ('usdt', models.FloatField(default=0)),
                ('wbtc', models.FloatField(default=0)),
                ('xlm', models.FloatField(default=0)),
                ('xmr', models.FloatField(default=0)),
                ('xrp', models.FloatField(default=0)),
                ('yfi', models.FloatField(default=0)),
                ('zec', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
