# Generated by Django 4.2.18 on 2025-02-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
