# Generated by Django 4.2.18 on 2025-02-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_delete_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='algo',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='atom',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='avax',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bat',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bond',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='dot',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='edu',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='eos',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='fxs',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='gala',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='gtc',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='hive',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='kava',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='mana',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='one',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='paxg',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='qnt',
        ),
    ]
