# Generated by Django 4.2.18 on 2025-01-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_wallet_naira_wallet_ton_alter_wallet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='naira',
            new_name='ngn',
        ),
    ]
