# Generated by Django 4.2.18 on 2025-02-26 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0004_remove_wallet_uni"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ada", models.FloatField(default=0)),
                ("bch", models.FloatField(default=0)),
                ("bnb", models.FloatField(default=0)),
                ("btc", models.FloatField(default=0)),
                ("busd", models.FloatField(default=0)),
                ("dash", models.FloatField(default=0)),
                ("doge", models.FloatField(default=0)),
                ("eth", models.FloatField(default=0)),
                ("ftm", models.FloatField(default=0)),
                ("link", models.FloatField(default=0)),
                ("ltc", models.FloatField(default=0)),
                ("matic", models.FloatField(default=0)),
                ("ngn", models.FloatField(default=0)),
                ("neo", models.FloatField(default=0)),
                ("ont", models.FloatField(default=0)),
                ("shib", models.FloatField(default=0)),
                ("sol", models.FloatField(default=0)),
                ("trx", models.FloatField(default=0)),
                ("ton", models.FloatField(default=0)),
                ("usdc", models.FloatField(default=0)),
                ("usdt", models.FloatField(default=0)),
                ("wbtc", models.FloatField(default=0)),
                ("xlm", models.FloatField(default=0)),
                ("xmr", models.FloatField(default=0)),
                ("xrp", models.FloatField(default=0)),
                ("yfi", models.FloatField(default=0)),
                ("zec", models.FloatField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
