# Generated by Django 4.2.18 on 2025-01-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_conversion_status_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
