# Generated by Django 4.2.18 on 2025-01-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='amount_from',
            new_name='qty_from',
        ),
        migrations.RenameField(
            model_name='conversion',
            old_name='amount_to',
            new_name='qty_to',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='qty',
        ),
    ]
