# Generated by Django 4.2.18 on 2025-01-29 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_rename_amount_from_conversion_qty_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
