# Generated by Django 4.2.18 on 2025-01-30 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_conversion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
