# Generated by Django 4.2.18 on 2025-01-30 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_conversion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
