# Generated by Django 4.2.18 on 2025-01-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_conversion_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
