# Generated by Django 4.2.18 on 2025-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_rename_date_conversion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='medium',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
