# Generated by Django 4.2.18 on 2025-02-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_transaction_medium_alter_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='network',
            field=models.CharField(default='bep20', max_length=10),
        ),
    ]
