# Generated by Django 4.2.18 on 2025-02-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_ticker_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='min',
            field=models.FloatField(default=1),
        ),
    ]
