# Generated by Django 4.2.18 on 2025-02-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_transaction_bank_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='max',
            field=models.FloatField(default=1000),
        ),
    ]
