# Generated by Django 4.2.18 on 2025-02-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_ticker_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_usd',
            field=models.FloatField(default=0),
        ),
    ]
