# Generated by Django 4.2.18 on 2025-02-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuser",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
