# Generated by Django 4.2.18 on 2025-03-10 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_accountdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="", max_length=20)),
                ("currency_name", models.CharField(default="", max_length=100)),
                ("address", models.CharField(default="", max_length=100)),
                ("network", models.CharField(default="", max_length=100)),
                ("key", models.CharField(default="", max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
