# Generated by Django 4.2.18 on 2025-03-11 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_webhook_webhookaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookaddress",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="webhookaddress",
            name="network",
            field=models.CharField(default="", max_length=20),
        ),
    ]
